#!/usr/bin/env bash

# Setup PATHS

### These paths are set by default
### /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools

# LLVM
#PATH=/usr/local/opt/llvm/bin:${PATH}

# Nim
PATH=${HOME}/.nimble/bin:${PATH}

# Rust
#PATH=${HOME}/.cargo/bin:${PATH}

# Golang
PATH=${GOPATH}/bin:${PATH}

# Sqlite3
PATH=/usr/local/opt/sqlite/bin:${PATH}

# coreutils
PATH=/usr/local/opt/coreutils/libexec/gnubin:${PATH}

# findutils
PATH=/usr/local/opt/findutils/libexec/gnubin:${PATH}

# grep
PATH=/usr/local/opt/grep/libexec/gnubin:${PATH}

# curl
PATH=/usr/local/opt/curl/bin:${PATH}

# Gettext
PATH=/usr/local/opt/gettext/bin:${PATH}

# flutter
PATH=${PATH}:${HOME}/sdks/flutter/bin

# Postgress app
PATH=/Applications/Postgres.app/Contents/Versions/latest/bin:${PATH}

# Language and SDK Version Managers

# Luaver Config (installed via git)
# Update using git:
# $ cd ~/.luaver && git fetch origin && git reset --hard origin/master
#[ -s ~/.luaver/luaver ] && . ~/.luaver/luaver

# Roswell Common Lisp
#PATH=${HOME}/.roswell/bin:${PATH}

# ASDF Config
# via homebrew
#. $(brew --prefix asdf)/asdf.sh

# Volta config
#[ -s "$VOLTA_HOME/load.sh" ] && . "$VOLTA_HOME/load.sh"
#PATH="${VOLTA_HOME}/bin:${PATH}"

# Poetry (ala Pipenv)
#PATH=${HOME}/.poetry/bin:${PATH}

# Doom emacs
PATH=${HOME}/.emacs.d/bin:${PATH}

# Setup MANPATH

# Export MANPATH
export MANPATH

# Export PGK_CONFIG_PATH
export PKG_CONFIG_PATH

# Export PATH
export PATH
