#!/usr/bin/env zsh

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/dotfiles/zsh/zprofile" ]]; then
  source /etc/zprofile
  source "${ZDOTDIR:-$HOME}/dotfiles/zsh/zprofile"
fi
