
### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zinit-zsh/z-a-rust \
    zinit-zsh/z-a-as-monitor \
    zinit-zsh/z-a-patch-dl \
    zinit-zsh/z-a-bin-gem-node

### End of Zinit's installer chunk


### Added

# Load aliases and functions
for file in ~/.{zaliases,functions}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file"
done
unset file

#neofetch
if [ -v ${VIRTUAL_ENV} ]; then
  neofetch
fi

fpath=(
  ~/.local/completions $fpath
)

# Command line keybinding
bindkey -e

# Two regular plugins loaded without investigating.
zinit light zsh-users/zsh-autosuggestions
zinit light zdharma/fast-syntax-highlighting

# Plugin history-search-multi-word loaded with investigating.
zinit load zdharma/history-search-multi-word

# Load the pure theme, with zsh-async library that's bundled with it.
zinit ice pick"async.zsh" src"pure.zsh"
zinit light sindresorhus/pure

# For GNU ls (the binaries can be gls, gdircolors, e.g. on OS X when installing the
# coreutils package from Homebrew; you can also use https://github.com/ogham/exa)
zinit ice atclone"dircolors -b LS_COLORS > clrs.zsh" \
  atpull'%atclone' pick"clrs.zsh" nocompile'!' \
  atload'zstyle ":completion:*" list-colors “${(s.:.)LS_COLORS}”'
zinit light trapd00r/LS_COLORS

# Binary release in archive, from GitHub-releases page.
# After automatic unpacking it provides program "fzf".
zinit ice from"gh-r" as"program"
zinit load junegunn/fzf-bin

# Direnv
zinit from"gh-r" as"program" mv"direnv* -> direnv" \
  atclone'./direnv hook zsh > zhook.zsh' atpull'%atclone' \
  pick"direnv" src="zhook.zsh" for \
    direnv/direnv

# z.lua
#eval "$(lua $HOME/github/utils/z.lua/z.lua --init zsh enhanced once fzf)"
zinit wait lucid id-as=zlua \
  atclone="lua z.lua --init zsh enhanced once fzf > zlua.gen.zsh" \
  atpull="%atclone" pick="zlua.gen.zsh" for \
    skywind3000/z.lua

# pipx completion
#eval "$(register-python-argcomplete pipx)"
# make this the last turbo mode loading due to the atload command
zinit wait lucid id-as=pipx \
  atclone="register-python-argcomplete pipx > pipx.gen.zsh" \
  atpull="%atclone" pick="pipx.gen.zsh" \
  atload"zicompinit; zicdreplay" blockf for \
    zdharma/null

# Zsh completions
#autoload -Uz compinit; compinit

# Bash completions
autoload -Uz bashcompinit; bashcompinit
